# This workflow will build a .NET Framework 4.5.2 project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET Framework 4.5.2 Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    # Setup .NET Framework 4.5.2 environment
    # Note: GitHub-hosted runners already include .NET Framework installations
    # So, there is no need to setup .NET version as it's for .NET Core or .NET 5/6

    - name: Restore NuGet packages
      run: nuget restore aspnet-get-started.sln

    - name: Build
      run: msbuild aspnet-get-started.sln /p:Configuration=Release /p:TargetFrameworkVersion=v4.5.2

    # Add steps for testing if you have tests to run
    # - name: Test
    #   run: path/to/your/test-runner
